#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# Luckily, PostgreSQL has an Alpine version ready to go, so we'll use that
# version to mount our database. There is no major configuration apart
# from pulling the latest image based on Alpine.
# 

FROM postgres:alpine
	
CMD ["postgres"]