#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# MariaDB is not supported in Alpine it seems, as the only way to get this
# RDBMS is to download the latest image made for MariaDB. There is not
# something wrong with this approach, but the image may be big.

FROM mariadb:latest

CMD ["mysqld"]