#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# We just need to call our PHP Container again, and add Xdebug.ini from the
# `docker-compose.yml`.

FROM shipyard_php:latest

# ENTRYPOINT [ "/init" ]

# WORKDIR /var/www